elementAdmin:
	ingress:
		host: admin.your.tld
elementWeb:
	ingress:
		host: chat.your.tld
matrixAuthenticationService:
	ingress:
		host: account.your.tld
matrixRTC:
	ingress:
		host: mrtc.your.tld
serverName: your.tld
synapse:
	ingress:
		host: matrix.your.tld